

# This is config generated by FeatureBox installer
# Devise need it as long as we want to use FeatureBox's views and contollers
Devise.setup do |config|
  config.parent_controller = "FeatureBox::ApplicationController"
  config.router_name = :feature_box
end